FROM ubuntu:20.04

RUN apt update

RUN apt upgrade -y

RUN apt-get install -y postfix nano dnsutils wget iputils-ping telnet dovecot-common dovecot-imapd dovecot-pop3d 

COPY main.cf /etc/postfix

COPY 10-mail.conf /etc/dovecot/conf.d

COPY 20-pop3.conf /etc/dovecot/conf.d

COPY dovecot.conf /etc/dovecot

# Add User
RUN useradd -c 'Bob' -m -s /bin/false Bob
RUN useradd -c 'Jeff' -m -s /bin/false Jeff

# Set user password
RUN echo "Bob:pwd123" | chpasswd
RUN echo "Jeff:pwd456" | chpasswd

CMD ["postfix", "start-fg"]
